### ISSUE TITLE
运行时，选择学院后，专业班级无法选择，仅有请选择专业

### ISSUE THREAD

**Issue by ghost** [huihut/stuManager#1]
在用你的数据库数据后，会出现这样的状况；但只加载数据库结构的没有问题。

**Comment by huihut** [comment]
1. “运行显示java.lang.NullPointerException”，可能是数据库没有连接好。
2. “用带数据的数据库有问题”，可能是我录入测试数据时有错误。

既然数据库结构没问题，那就自己录入数据吧！:-)
