### ISSUE TITLE
ER图内的各个表之间为何没有线连接

### ISSUE THREAD

**Issue by GeneralLi95** [huihut/stuManager#2]
我自己也使用workbench进行了逆向操作，得到的结果与您的一致，但是还是不太明白为何，各个表格之间的结果会没有连线呢，这些表格之间就是独立的么？

**Comment by huihut** [comment]
因为这个数据库设计得不满足第三范式，没有消除主属性对码的传递函数依赖，所以各表间没有线，只是通过代码对有关系的非主属性进行连并增删的。我写这课设时还没学过数据库，所以设计成这样，更优的数据库设计应该满足第三范式（E-R图有线那种）的。

**Comment by GeneralLi95** [comment]
@huihut 明白了，我在操作的时候也发现了，对删除某个课程之后，已经有这么课程的学生却没有受到影响。还是学到很多，谢谢啦。

**Comment by huihut** [comment]
这个应该是那里代码中忘记删了，所以写得很渣，见笑了。[捂脸]
