### ISSUE TITLE
Please optimize the extensibility of your code.

### ISSUE THREAD

**Issue by GoogTech** [huihut/stuManager#4]
https://github.com/huihut/stuManager/blob/c9ec020966d9a2300bc07f0da05d2cc407a4db90/src/db/dbConn.java#L28

 :exclamation: suggest use the propertiy file to store these database information !

**Comment by huihut** [comment]
Sorry, this project is no longer maintained.

**Comment by YUbuntu0109** [comment]
😶 ok,Just hope things get better.

**Comment by GoogTech** [comment]
> 
> 
> Sorry, this project is no longer maintained.

😶  ok,Just hope things get better.
